apiVersion: v1
kind: Service
metadata:
  name: code-service
  namespace: code-server
spec:
  selector:
    app: code-server
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8443
    name: http
  type: LoadBalancer
  loadBalancerIP: 10.100.99.131
